SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT BAIRRO, CIDADE, CPF, NOME FROM TABELA_DE_CLIENTES;

SELECT CPF AS INDENTIFICADOR, NOME AS [NOME DO CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;
