-- Fazendo consultas com filtros
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '290478';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'laranja';
SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';



