-- Contar quantos dados temos em cada tabela
SELECT COUNT(*) FROM [TABELA_DE_CLIENTES];
SELECT COUNT(*) FROM [TABELA_DE_PRODUTOS];
SELECT COUNT(*) FROM [TABELA_DE_VENDEDORES];
SELECT COUNT(*) FROM [NOTAS_FISCAIS];
SELECT COUNT(*) FROM [ITENS_NOTAS_FISCAIS];