SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 22;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE >= 22;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 22;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <= 22;

-- SELECIONAR OS CLIENTES DIFERENTE DE 22 ANOS
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 22;

-- FILTROS COM DATA EX: YYYY-MM-DD
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO = '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO > '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO < '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <= '1995-11-14';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO <> '1995-11-14';
