-- NOMEANDO OS NOMES DAS COLUNAS OU SEJA VAMOS DAR APELIDOS AS COLUNAS
SELECT [NOME] AS [NOME DO CLIENTE],
	[ESTADO] AS [UF]
	FROM [TABELA DE CLIENTES];

SELECT [NOME DO PRODUTO] AS [PRODUTO],
	[PRECO DE LISTA] AS [R$]
	FROM [dbo].[TABELA DE PRODUTOS];

SELECT [NOME] AS [NOME DO VENDEDOR],
	[COMISSAO] AS [%]
	FROM [TABELA DE VENDEDORES];

-- PEGANDO TODOS OS SABORES DOS SUCOS SEM REPETIR O SABOR
SELECT [SABOR] FROM [TABELA DE PRODUTOS];
SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS];